-- Creating a new user 
create USER IDENTIFIER('"AMBIKA"') COMMENT = 'this is a trial role ' PASSWORD = '☺☺☺☺☺' MUST_CHANGE_PASSWORD = false LOGIN_NAME = 'ambi' FIRST_NAME = 'Ambika' LAST_NAME = 'Nishad' DISPLAY_NAME = 'Ambika' EMAIL = '' DEFAULT_WAREHOUSE = 'COMPUTE_WH' DEFAULT_NAMESPACE = '' DEFAULT_ROLE = 'SYSADMIN';

GRANT ROLE IDENTIFIER('"SYSADMIN"') TO USER IDENTIFIER('"AMBIKA"');

